### ISSUE TITLE
question about pruning ratio

### ISSUE THREAD

**Issue by Anonymous-f** [henryqin1997/InfoBatch#10]
Hi, thanks for sharing your excellent work! I have a question about the pruning ratio. When the ratio is set to 0.5, does it mean pruning 50% of the whole dataset or only pruning 50% of samples that are smaller than the average?  I found when the ratio=0.5, only about 10000 samples are pruned in the provided example.

**Comment by henryqin1997** [comment]
It is pruning 50% of samples that are smaller than the average, so this way of sample selection will depend on loss distribution. Based on theoretical analysis, sample selection is not restricted to using average; later we will provide another version that can losslessly save 40% on CIFAR100.
